name = "claude-code-worker"
type = "javascript"
main = "worker.js"
compatibility_date = "2024-05-01"

[[d1_databases]]
binding = "DB"
database_name = "claude_code_db"
database_id = "<your-d1-database-id>"